language: node_js
node_js:
  - "0.10"

script:
  - node_modules/.bin/jspm install
  - node_modules/gulp/bin/gulp.js dev-no-watch
  - node_modules/karma/bin/karma start --single-run

cache:
  directories:
    - node_modules
    - jspm_packages
